### ISSUE TITLE
请问网站底部的字体怎么修改啊？

### ISSUE THREAD

**Issue by krzer** [shijiebei2009/MyThemes#1]

**Comment by shijiebei2009** [comment]
主题字体修改文件D:\hexo\themes\jacman\source\css_base\variable.styl文件，做如下修改：
//font-custom-family = “covered_by_your_graceregular”
//font-custom-filename = coveredbyyourgrace-webfont
font-custom-family = “Helvetica Neue”
font-custom-filename = fontdiao

**Comment by krzer** [comment]
恩恩，明白了，谢谢了！
